In [16]:
!pip install numpy

import numpy as np

In [17]:
# Array Creation

a = np.array(10)
type(a)

numpy.ndarray

In [4]:
# zero dimensional array

z = np.array(10)
z.ndim

0

In [5]:
#1 dimensional array

b = np.array([10,11,12,13])
b.ndim

1

In [6]:
# 2 Dimenstional array

c = np.array([[10,12,13,14,15]])
c.ndim

2

In [9]:
# 3 Dimenstional array

three = np.array([[[10,12,13,14,15]]])

three.ndim

3

In [10]:
# change data typeinto other type

a = np.array([12,13,14,15,18,17])

a.dtype

dtype('int32')

* Change the data type of array elements

In [13]:
a = np.array([11,12,13,14,15],dtype = 'float')
print(a.dtype)
print('Hello')
a

float64
Hello


array([11., 12., 13., 14., 15.])

* Other ways of creating an array
* 1 arrange
* 2 linspace
* 3 zer

In [20]:
# Arrange

a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
# 2 Linespace

b = np.linspace(1,5,15)

b

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [22]:
# Random

r = np.random.rand(5,5)
r

array([[0.61057695, 0.99989222, 0.78086187, 0.13431641, 0.82987479],
       [0.71615847, 0.6391529 , 0.70592094, 0.8517119 , 0.28480068],
       [0.16832914, 0.12073389, 0.71854269, 0.65133769, 0.11609581],
       [0.46257923, 0.940044  , 0.96687632, 0.85344875, 0.68652476],
       [0.06672835, 0.1328488 , 0.66142005, 0.80345431, 0.6016389 ]])

In [23]:
R1 = np.random.randint(5,size=10)
R1

array([0, 2, 4, 4, 2, 2, 4, 2, 4, 0])

# Slicing and Indexing of arrays

In [25]:
a = np.array([[1,2,3],[4,5,6]])

a

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a[0,0]

1

In [28]:
# Find (6)

a[1,2]

6

In [29]:
# Find (2,3)

a[0,1:]

array([2, 3])

In [30]:
# Find (2,3),(5,6)

a[0:,1:]

array([[2, 3],
       [5, 6]])

In [32]:
# 3 and 4

a[[0,1],[2,0]]

array([3, 4])

# Reshaping the arrays

In [33]:
a = np.random.rand(5,2)

In [34]:
a

array([[0.50726336, 0.00792032],
       [0.06216138, 0.01030762],
       [0.26806785, 0.14225372],
       [0.38346238, 0.56100614],
       [0.34442216, 0.82510355]])

In [35]:
a.reshape(2,5)

array([[0.50726336, 0.00792032, 0.06216138, 0.01030762, 0.26806785],
       [0.14225372, 0.38346238, 0.56100614, 0.34442216, 0.82510355]])

In [36]:
a.reshape(10,1)

array([[0.50726336],
       [0.00792032],
       [0.06216138],
       [0.01030762],
       [0.26806785],
       [0.14225372],
       [0.38346238],
       [0.56100614],
       [0.34442216],
       [0.82510355]])

In [37]:
a.reshape(5,2)

array([[0.50726336, 0.00792032],
       [0.06216138, 0.01030762],
       [0.26806785, 0.14225372],
       [0.38346238, 0.56100614],
       [0.34442216, 0.82510355]])

In [38]:
a.reshape(1,10)

array([[0.50726336, 0.00792032, 0.06216138, 0.01030762, 0.26806785,
        0.14225372, 0.38346238, 0.56100614, 0.34442216, 0.82510355]])

In [39]:
a.reshape(5,-1)

array([[0.50726336, 0.00792032],
       [0.06216138, 0.01030762],
       [0.26806785, 0.14225372],
       [0.38346238, 0.56100614],
       [0.34442216, 0.82510355]])

# Aggregate Function

In [40]:
a.min()

0.007920320944470371

In [41]:
a.std()

0.25420555061863004

In [42]:
a.var()

0.06462046196532087

# Stacking

* vertical stacking
* Horizontal Staking

In [44]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

In [45]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [46]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])